### ISSUE TITLE
using time() as cooldown over task

### ISSUE THREAD

**Issue by Thunder33345** [CaptainDuck/GappleCooldown#2]
since using task are redundant and abuse of the system to begin with
and there's no need for realtime notice if the cooldown goes off thus it shouldnt be needed
you should just put `time() + cooldown` into the array
which can easily be checked by 
`if time() > value `

**Comment by CaptainDuck** [comment]
Awesome, thanks! this should help with optimization :)

**Comment by Thunder33345** [comment]
still not fixed??

**Comment by CaptainDuck** [comment]
Working on it :)

**Comment by CaptainDuck** [comment]
How can I check the seconds left?

time() - cooldown

And to check I can use
time >= cooldown right?

**Comment by Thunder33345** [comment]
to register
`cooldown_until = time()+(cooldown in seconds)`
basically set a variable of current time + how long to wait for

to check
`if time() > cooldown_until `
now we check if the current time past when we waited for
