### ISSUE TITLE
Crashes the server

### ISSUE THREAD

**Issue by minijaham** [CaptainDuck/GappleCooldown#7]
When consuming gapples, first off, gapple cooldown doesn’t even work and eggaps, when you eat it for the second time, you just crash.

**Comment by GarsonGV** [comment]
How do I fix this problem ???

**Comment by GarsonGV** [comment]
> When consuming gapples, first off, gapple cooldown doesn’t even work and eggaps, when you eat it for the second time, you just crash.
How do I fix this problem ???

**Comment by minijaham** [comment]
> > When consuming gapples, first off, gapple cooldown doesn’t even work and eggaps, when you eat it for the second time, you just crash.
> > How do I fix this problem ???

Bro that's what I need .-.

**Comment by CaptainDuck** [comment]
Can you send the error in console?
The problem may be that you're using the outdated resource files, can you delete them then check if the problem still occurs?

**Comment by minijaham** [comment]
Yes sure

**Comment by minijaham** [comment]
Oh nevermind. I downloaded the Zip file and converted that to phar and now it's working! Only the .phar version in poggit isn't working. Maybe it's because the API is 3.0.0. Try setting it to 
[3.0.0, 4.0.0] in plugin.yml
It worked when I added 4.0.0
